### ISSUE TITLE
Missing tfm gui

### ISSUE THREAD

**Issue by dww52** [olschwab/cardiomyocyte_guis_stanford#1]
Hi, 
I just finished reading your paper in Circulation, "Multi-Imaging Method to Assay the Contractile Mechanical Output of Micropatterned Human iPSC-Derived Cardiac Myocytes". I'm trying to run your TFM GUI, but it appears the tfm_gui_main.m file is missing. Should it be under the "traction_force_microscopy_GUI" folder? I haven't been able to find it there.

**Comment by dww52** [comment]
I see that beads_main.m seems to open the GUI. Is this the correct way to initialize the GUI?

**Comment by olschwab** [comment]
Hi,

Yes, to start using the GUIs, call the file *_main.m for each GUI. All other m-files do not need to be called by the user (they are at some point invoked by *_main.m). For TFM, the main file seems to be called beads_main.m instead of tfm_gui_main.m. If this is wrong in the manuals, I apologize and will update the documentation.

Hope everything else is working fine :)
